Repository SoftEng-HEIGVD/Teaching-HEIGVD-RES-2020-Chill, pull requests merged in 2020-02, with the labels that each got.

#15 Definitly need some Coke
  src/main/java/ch/heigvd/res/chill/domain/mikeDTr/Coke.java
  src/test/java/ch/heigvd/res/chill/domain/mikeDTr/CokeTest.java
Labels: bug

#64 Fb chimaek
  src/main/java/ch/heigvd/res/chill/domain/0x47726579/Chimaek.java
  src/test/java/ch/heigvd/res/chill/domain/0x47726579/ChimaekTest.java
Labels: wrong package

#62 Fb hite
  src/main/java/ch/heigvd/res/chill/domain/0x47726579/Hite.java
  src/test/java/ch/heigvd/res/chill/domain/0x47726579/HiteTest.java
Labels: wrong package

#54 First version of Kwak
  src/main/java/ch/heigvd/res/chill/domain/ClarFleu/Kwak.java
  src/test/java/ch/heigvd/res/chill/domain/ClarFleu/KwakTest.java
Labels: wrong package

#110 Merge to add Torpille Closes #108 Florian Mulhauser
  src/main/java/ch/heigvd/res/chill/domain/FlorianMulhauser/Torpille.java
  src/test/java/ch/heigvd/res/chill/domain/FlorianMulhauser/TorpilleTest.java
Labels: too many features

#72 Fanta added
  src/main/java/ch/heigvd/res/chill/domain/Ikewolf77/Fanta.java
  src/test/java/ch/heigvd/res/chill/domain/Ikewolf77/FantaTest.java
Labels: wrong package

#76 ajout de Queue de Charrue et Queue de Charrue test
  src/main/java/ch/heigvd/res/chill/domain/wasadigi/QueueDeCharrue.java
  src/test/java/ch/heigvd/res/chill/domain/wasadigi/QueueDeCharrueTest.java
Labels: wrong package

#65 Add Hoegaarden as new Product
  src/main/java/ch/heigvd/res/chill/domain/KurohanaJuri/Hoegaarden.java
  src/test/java/ch/heigvd/res/chill/domain/KurohanaJuri/HoegaardenTest.java
Labels: wrong package

#46 ajout de la leffe
  src/main/java/ch/heigvd/res/chill/domain/scout407/Leffe.java
  src/test/java/ch/heigvd/res/chill/domain/scout407/LeffeTest.java
Labels: wrong package

#56 Added a new beer
  src/main/java/ch/heigvd/res/chill/domain/ClarFleu/FinDuMonde.java
  src/test/java/ch/heigvd/res/chill/domain/ClarFleu/FinDuMondeTest.java
Labels: too many features

#154 Addition of Dies Irae
  src/main/java/ch/heigvd/res/chill/domain/GTZL1/DiesIrae.java
  src/test/java/ch/heigvd/res/chill/domain/GTZL1/DiesIraeTest.java
Labels: invalid
